### ISSUE TITLE
Pause button and animation not restarting

### ISSUE THREAD

**Issue by surfdemon** [surfdemon/whack-a-mole#35]
When pressing the pause button the game pauses but pressing it again doesn't make the game start up again as the plumbers don't start moving again. The timer at the top of the screen also doesn't start again. 

There is an error in the console... 
"
game.js:33 Uncaught ReferenceError: isPaused is not defined
    at window.pauseGame (game.js:33:5)
    at HTMLImageElement.<anonymous> (mainMenu.js:66:13)
"

**Comment by NSJ021** [comment]
Tweak buttons, possibly merge play/pause, possibly remove settings button as currently not function or in scope

**Comment by surfdemon** [comment]
fixed, play button now toggles between play button and pause button and restarting the game now doesn't speed it up.
